#!/usr/bin/env bash
# redirection

sudo apt update
sudo apt install nginx -y

sudo bash -c "echo 'Hello World!' > /var/www/html/index.html"

sudo service nginx start

sudo sed -i '53i\\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.facebook.com\/;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
