#!/usr/bin/env bash
# Configure Nginx so that its HTTP response 

var=$(hostname)
new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.facebook.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

apt-get update -y
apt-get install nginx -y

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html > /dev/null
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default

sudo service nginx start
