#!/usr/bin/env bash
#Script to install and configure HAProxy on lb-01 server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes
backend nodes
	mode http
	balance roundrobin
	server 1346-web-01 197.211.58.187
	server 1346-web-02 102.91.4.102" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
