#!/usr/bin/env bash
# Displays "To infinity and beyond" with
# a sleep 2 in between each iteration.
# then "I am invincible!!!" in bwt each iteration.

trap "echo I am invincible!!!" SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
