#!/usr/bin/env bash
# Bash script that fixs
pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
